# Generated by Django 6.0.2 on 2026-04-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='number',
            new_name='phone',
        ),
    ]
