# Generated by Django 6.0.2 on 2026-04-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_number_patient_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Time',
            new_name='time',
        ),
    ]
